config/routes.rb
Rails.application.routes.draw do
  root "static_pages#root"
  resources :admins, only: [:new, :create, :edit, :update, :destroy, :show]
  resources :quizzes,only: [:new, :edit]
  resources :quizzes,except: [:new, :edit], defaults: {format: :json} do

    collection do
      get :admin_index, defaults: {format: :html}
      get ':admin_show/:id', :to => 'quizzes#admin_show', :as => :'admin_show', defaults: {format: :html}
    end

    resources :questions, defaults: {format: :html} do
    # get :admin_show, defaults: {format: :html}
      resources :answers, defaults: {format: :html}
    end

  end

  resources :answer_choices, only: [:create, :index]
  resources :user_quizzes, only: [:create, :show, :index]

  namespace :test, defaults: {format: :json} do
    post "post_answer_choice", to: "answer_choices#create"
    # resources :answer_choices, only: [:create]
  end
end

# localhost:3000/test/post_answer_choice

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def new
    @quiz = Quiz.new
  end

# this is a custom route, to view all of the tests in a clickable fashion
  def admin_index
    @quizzes = Quiz.all
    render :admin_index

  end



  def index
    @quizzes = Quiz.all
    render :index
  end

  def create
    @quiz = Quiz.new(quiz_params)


    if @quiz.save
      redirect_to admin_index_quizzes_url
    else
      render json: @quiz.errors.full_messages, status: 422
    end
  end

    def show

      @quiz = Quiz.find(params[:id])
    end

    def admin_show

        @quiz = Quiz.find(params[:id])
    end

    def edit
      @quiz = Quiz.find(params[:id])
    end

    def update
      @quiz = Quiz.find(params[:id])

      if @quiz.update(quiz_params)
        redirect_to '/quizzes/admin_show/' + @quiz.id.to_s + '/'
      else
        render :edit
      end
    end

    def destroy
     @quiz = Quiz.find(params[:id])
     @quiz.destroy
     redirect_to '/quizzes/admin_index/'
    end

  private

  def quiz_params
    params.require(:quiz).permit(
      :title, :day, :max_time, :number_of_questions
    )
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/admin_index.html.erb
<div class="admin-nav">
  <div style="  float: left;
    padding: 30px;
    padding-left: 100px;
    font-size: 24px;">App Academy Teacher Portal</div>
</div>


<h3 class="admin-header">Quizzes</h3>


<% @quizzes.each do |quiz| %>
<br>
<div class="admin-quiz-box">
  <div class="admin-quiz-name">
     <a style="color:blue;"
        href="http://localhost:3000/quizzes/admin_show/<%= quiz.id %>/"> <%= quiz.title %> </a>
  </div>
    <br>
    <label>Number of Questions:</label>
    <%= quiz.number_of_questions %>
    <br>
    <label>Quiz Day:</label>
    <%= quiz.day %>
    <br>
    <label>Time Allowed:</label>
    <%= quiz.max_time %>

    <br>
    <div class="box-delete-button">
      <%= link_to "Delete Quiz", quiz_url({id: quiz.id}), method: :delete %>
    </div>
    <div class="box-edit-button">
      <%= link_to "Edit Quiz", edit_quiz_path(quiz.id)%>
    </div>
  </div>

  <% end %>
  <br>

<br>
<br>
<a class="add-quiz-button"
href="/quizzes/new"> Add a Quiz </a>

<br>
<br>

</a>

app/views/quizzes/admin_show.html.erb
<div class="admin-nav">
  <div style="  float: left;
    padding: 30px;
    padding-left: 100px;
    font-size: 24px;">App Academy Teacher Portal</div>
</div>



<a class="back-to-edit-button" href="/quizzes/admin_index/"> Return to Test List </a>
<br><br>
<div class="quiz-info">
Quiz Title:
<%= @quiz.title %> </a>
<br>
<label>Number of Questions:</label>
<%= @quiz.number_of_questions %>
<br>
<label>Quiz Day:</label>
<%= @quiz.day %>
<br>
<label>Time Allowed:</label>
<%= @quiz.max_time %>
</div>

<% @quiz.questions.each do |question| %>

  <div class='quiz-admin-show-individual'>
    <br>
    <div class="green-submit-button">
    <%= link_to "Edit Question", edit_quiz_question_path({id: question.id, quiz_id:@quiz.id})%>
    </div>
    <br>

    Question:
    <%= question.text%>
    <br>
    Type:
    <%= question.question_type%>
    <br>
    <% if question.correct_answer_id === nil %>
    <div style="color:red;">No Correct Answer Selected</div>
    <br>
    <% else %>
    Correct answer:
    <%= question.correct_answer.text%>
    <br>
    <% end %>
    Explanation:
    <%= question.explanation %>

  <div class="answers">
    Answer:

    <form action="/quizzes/<%=question.quiz_id%>/questions/<%=question.id%>" method="post">
        <input type="hidden" name="_method" value="patch">

          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
      <% question.answers.each do |answer| %>
        <br>
        <% if answer.id === question.correct_answer_id %>

          <input type="radio"
                name="question[correct_answer_id]"
                value="<%= answer.id%>"
                style="margin:3px; margin-bottom: 25px;"
                checked
                onclick=this.form.submit();>
                <%= answer.text%>
                <div class="red-delete-answer">
                  <%= link_to "Delete Answer",
                  quiz_question_answer_url({quiz_id: @quiz.id,question_id: question.id  , id: answer.id }), method: :delete %>
                </div>


      <% else %>

        <input type="radio"
              name="question[correct_answer_id]"
              value="<%= answer.id%>"
              style="margin:3px; margin-bottom: 25px;"
              onclick=this.form.submit();>
              <%= answer.text%>
              <div class="red-delete-answer">
                <%= link_to "Delete Answer",
                quiz_question_answer_url({quiz_id: @quiz.id,question_id: question.id  , id: answer.id }), method: :delete %>
              </div>


      <% end %>
      <div class="green-edit"
        <%= link_to "Edit Answer", edit_quiz_question_answer_path({id: answer.id, question_id: question.id, quiz_id: @quiz.id})%>
      </div>
    <% end %>
    </form>
    <div class="quiz-stats">
      <!-- We need the answer choices so we can tally and then make the graphs -->
      <br>
      Question Results:
      <% answers = Hash.new(0) %>
      <% question.answer_choices.each {|el| answers[el.answer.text] += 1 } %>
      <%= pie_chart answers %>
    </div>

  </div>

  <a style="background-color:#4285F4;
          -moz-border-radius:28px;
          -webkit-border-radius:28px;
          border-radius:28px;
          border:1px solid #18ab29;
          display:inline-block;
          cursor:pointer;
          color:#ffffff;
          font-family:'Lato';
          font-size:12px;
          padding:5px 10px;
          text-decoration:none;
          text-shadow:0px 1px 0px #2f6627;"
  href="/quizzes/<%= @quiz.id %>/questions/<%=question.id%>/answers/new"> Add an Answer </a>
<div style="background-color:red;
        -moz-border-radius:28px;
        -webkit-border-radius:28px;
        border-radius:28px;
        border:1px solid #18ab29;
        display:inline-block;
        cursor:pointer;
        color:#ffffff;
        font-family:'Lato';
        font-size:12px;
        padding:5px 10px;
        text-decoration:none;
        text-shadow:0px 1px 0px #2f6627;
        float: right;">
  <%= link_to "Delete Question", quiz_question_url({id: question.id, quiz_id: @quiz.id}), method: :delete %>
</div>
<br>
</div>
<% end %>

<div style='margin-bottom:100px;'>
<a class="add-a-question-button"
href="/quizzes/<%= @quiz.id %>/questions/new"> Add a Question </a>
</div>

app/views/quizzes/edit.html.erb
<div class="admin-nav">
  <div style="  float: left;
    padding: 30px;
    padding-left: 100px;
    font-size: 24px;">App Academy Teacher Portal</div>
</div>
<h3 class="admin-header">Edit this quiz</h3>
<br>

<form action="<%= quiz_url(@quiz) %>" method="post" class='quiz-edit-form'>
  <input type="hidden" name="_method" value="PATCH">

    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">


    <label for="quiz_title">Quiz Title</label>
    <input type="text"
           name="quiz[title]"
           style="border: solid 1px #969696;"
           value="<%= @quiz.title %>">
    <br>
    <label for="quiz_day">Quiz Day:  Ex. "W1D1"</label>
    <input type="text"
           name="quiz[day]"
           style="border: solid 1px #969696;"
           value="<%= @quiz.day %>">
     <br>
     <label for="quiz_max_time">Minutes allowed:   Ex. 60</label>
     <input type="text"
            name="quiz[max_time]"
            style="border: solid 1px #969696;"
            value="<%= @quiz.max_time %>">
      <br>
      <label for="quiz_number_of_questions">Number of questions on the quiz:</label>
      <input type="text"
             name="quiz[number_of_questions]"
             style="border: solid 1px #969696;"
             value="<%= @quiz.number_of_questions %>">

      <br>



    <input type="submit" value="Edit Quiz" id="quiz-edit-submit">
  </form>

</form>

app/views/quizzes/new.html.erb
<div class="admin-nav">
  <div style="  float: left;
    padding: 30px;
    padding-left: 100px;
    font-size: 24px;">App Academy Teacher Portal</div>
</div>
<h3 class="admin-header">Create a new quiz</h3>
<br>

<form action="<%= quizzes_url %>" method="post" class="quiz-edit-form">

    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">


    <label for="quiz_title">Quiz Title</label>
    <input type="text"
           name="quiz[title]"
           style="border: solid 2px #969696;"
           value="<%= @quiz.title %>">
    <br>
    <label for="quiz_day">Quiz Day:  Ex. "W1D1"</label>
    <input type="text"
           name="quiz[day]"
           style="border: solid 2px #969696;"
           value="<%= @quiz.day %>">
     <br>
     <label for="quiz_max_time">Minutes allowed:   Ex. 60</label>
     <input type="text"
            name="quiz[max_time]"
            style="border: solid 2px #969696;"
            value="<%= @quiz.max_time %>">
      <br>
      <label for="quiz_number_of_questions">Number of questions on the quiz:</label>
      <input type="text"
             name="quiz[number_of_questions]"
             style="border: solid 2px #969696;"
             value="<%= @quiz.number_of_questions %>">

      <br>



    <input type="submit" value="Submit Quiz" id="quiz-edit-submit">
  </form>

</form>